Adds support for WordPress CLI
MITLibraries/wp_mitlibraries_docker pull request #5
Opened 2020-04-13 14:34 UTC by JPrevost

**IMPORTANT NOTE: this moves the linked directory up a level in the docker container from `wp-content` to `html`, which is linked as `wp-app` locally. Because of this, it's best to probably start over with your local setup to get it to all synch up correctly.** This change was necessary to allow the WordPress CLI to work.

Most of the changes to `docker-compose.yml` are whitespace. The important bits are the `wpcli` stanza.

This adds support for arbitrary WordPress CLI commands in our Docker
environment.

It also adds some `make` commands to simplify some common development
tasks in this Docker environment.

2020-04-13 14:38 UTC, JPrevost commented on package-lock.json
> +  "lockfileVersion": 1
Hmmm. I'm not sure what this is all about.

2020-04-13 19:44 UTC, jazairi approved these changes
Confirmed that the `make` commands all work. 👍 I'm having trouble finding the parent theme, but I think that's a me problem (having the same issue in master).

2020-04-13 21:18 UTC, matt-bernhardt requested changes
It seems like the plugins listed in `composer.json` aren't being installed to the expected locations. I can see them being installed by `composer install` (or `make install`) but then they don't appear in the plugin list either via `make plugins` or in the WP admin UI. Inspecing the filesystem shows that Composer put them directly into `./wp-content/...` rather than `./wp-app/wp-content/...`

I suspect that what's going to be needed is the `installer-paths` syntax in an `extra` block, similar to what was added here: https://github.com/MITLibraries/mitlib-wp-demo/blob/master/composer.json#L60-L64

2020-04-14 13:35 UTC, JPrevost commented
@matt-bernhardt doh. I'll take a peek today.

2020-04-14 20:28 UTC, matt-bernhardt approved these changes
This looks good! The contrib projects show up in the expected place in the filesystem and the admin UI.

:shipit:

2020-04-15 13:02 UTC, merged